version: "3.7"

services:

  pbs-ubuntu16.04:

    # not available so far
    # environment:
    #   - HOST=pbshost

    # keep alive ( not available so far )
    # tty: true
    # stdin_open: true

    build:
      context: ./
      dockerfile: Dockerfile
      args:
        # depends on the .env file
        HOST: ${HOST}

    image: "cetusk/pbs-ubuntu16.04:latest"

    container_name: "worker"

    # depends on the .env file
    hostname: ${HOST}

